<?php

namespace AppBundle\Repository;

/**
 * AesaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AesaRepository extends \Doctrine\ORM\EntityRepository
{
}
