<?php

namespace AppBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
    public function MyfindAllAnnonces(){
        $query = $this->_em->createQuery('SELECT a FROM AppBundle:Annonce a ORDER BY a.date ');
        return $query->getResult();
    }

    public function findOrderByDate()
    {
    $qb = $this->createQueryBuilder('a')
        ->orderBy('a.date', 'DESC');
    return $qb->getQuery()
        ->getResult();
    }
}
