<?php

namespace AppBundle\Repository;

/**
 * CertificatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertificatRepository extends \Doctrine\ORM\EntityRepository
{
    public function countByetudiant($etudiant){
        $query = $this->_em->createQuery('SELECT COUNT(a.etudiant) AS quantCertificat FROM AppBundle:Certificat a WHERE a.etudiant = :etudiant GROUP BY a.etudiant');
        $query->setParameter('etudiant', $etudiant);
        return $query->getOneOrNullResult();
    }
}
