<?php

namespace AppBundle\Repository;

/**
 * ConcerneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcerneRepository extends \Doctrine\ORM\EntityRepository
{
}
