<?php

namespace AppBundle\Repository;

/**
 * EntrepriseMereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrepriseMereRepository extends \Doctrine\ORM\EntityRepository
{
}
