<?php

namespace AppBundle\Repository;

/**
 * Entreprise_etudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Entreprise_etudiantRepository extends \Doctrine\ORM\EntityRepository
{
}
