<?php

namespace AppBundle\Repository;

/**
 * EntrepriseSuperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrepriseSuperRepository extends \Doctrine\ORM\EntityRepository
{
}
