<?php

namespace AppBundle\Repository;

/**
 * EntrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrepriseRepository extends \Doctrine\ORM\EntityRepository
{
    /*
    public function countByetudiant($etudiant){
        $query = $this->_em->createQuery('SELECT COUNT(a.etudiant) AS quantEntre FROM AppBundle:Entreprise a JOIN AppBundle:Entreprise_etudiant ea  WHERE a.entreprise_etudiant = ea.entreprises AND ea.etudiants =: etudiant GROUP BY a.etudiant');
        $query->setParameter('etudiant', $etudiant);
        return $query->getOneOrNullResult();
    }*/
}
