<?php

namespace AppBundle\Repository;

/**
 * EssaieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EssaieRepository extends \Doctrine\ORM\EntityRepository
{
}
