<?php

namespace AppBundle\Repository;

/**
 * EtudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMatrucule($matricule){
        $query = $this->_em->createQuery('SELECT a FROM AppBundle:Etudiant a WHERE a.matricule = :matricule');
        $query->setParameter('matricule', $matricule);
        return $query->getArrayResult();
    }

    public function findUserEtudiant($mail){
        $query = $this->_em->createQuery('SELECT a FROM AppBundle:Etudiant a WHERE a.email = :email');
        $query->setParameter('email', $mail);
        return $query->getOneOrNullResult();
    }
}
