etudiant_acceuille:
    path:     /acceuille
    defaults: { _controller: "AppBundle:Etudiant:acceuille" }
    methods:  GET

etudiant_index:
    path:     /
    defaults: { _controller: "AppBundle:Etudiant:index" }
    methods:  GET

etudiant_matricule:
    path:     /verif
    defaults: { _controller: "AppBundle:Etudiant:matricule" }
    methods:  GET

etudiant_user:
    path:     /userEtudiant
    defaults: { _controller: "AppBundle:Etudiant:etudiantUser" }
    methods:  [GET,POST]

etudiant_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Etudiant:show" }
    methods:  GET

etudiant_show_etudiant:
    path:     /{id}/showEtudiant
    defaults: { _controller: "AppBundle:Etudiant:showEtudiant" }
    methods:  GET

etudiant_new:
    path:     /new
    defaults: { _controller: "AppBundle:Etudiant:new" }
    methods:  [GET, POST]

etudiant_addPhoto:
    path:     /photo
    defaults: { _controller: "AppBundle:Etudiant:addPhoto" }
    methods:  POST

etudiant_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Etudiant:edit" }
    methods:  [GET, POST]

etudiant_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Etudiant:delete" }
    methods:  DELETE
