universite_index:
    path:     /
    defaults: { _controller: "AppBundle:Universite:index" }
    methods:  GET

universite_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Universite:show" }
    methods:  GET

universite_new:
    path:     /new
    defaults: { _controller: "AppBundle:Universite:new" }
    methods:  [GET, POST]

universite_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Universite:edit" }
    methods:  [GET, POST]

universite_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Universite:delete" }
    methods:  DELETE
