utilisateur_index:
    path:     /
    defaults: { _controller: "AppBundle:Utilisateur:index" }
    methods:  GET

utilisateur_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Utilisateur:show" }
    methods:  GET

utilisateur_show_entreprise:
    path:     /{id}/showEntreprise
    defaults: { _controller: "AppBundle:Utilisateur:showEntreprise" }
    methods:  GET

utilisateur_new:
    path:     /new
    defaults: { _controller: "AppBundle:Utilisateur:new" }
    methods:  [GET, POST]

utilisateur_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Utilisateur:edit" }
    methods:  [GET, POST]

utilisateur_edit_entreprise:
    path:     /{id}/editEntreprise
    defaults: { _controller: "AppBundle:Utilisateur:editEntreprise" }
    methods:  [GET, POST]

utilisateur_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Utilisateur:delete" }
    methods:  DELETE
